### ISSUE TITLE
Service-Accounts für 3rd-Party-Integration

### ISSUE THREAD

**Issue by SniperSister** [SIWECOS/siwecos-business-layer#100]
Servus Zusammen,

wir haben eine Anfrage von Plesk, die wollen eine SIWECOS-Extension für ihre Plattform bauen und haben hierbei ein paar abweichende Wünsche für das Verhalten der API:

1. automatische Registrierung: damit der Nutzer nach der Installation der Extension keine manuellen Aktionen mehr vornehmen muss, soll die Registrierung eines Benutzeraccounts automatisiert werden. Das würde bedeuten:
* kein Captcha
* kein Double-Opt-In
* Flag in der DB dass das ein Service-Account ist

2. keine Notifications oder Recurrent Scans - beides läuft direkt über Plesk, könnte dann in Abhängigkeit vom DB-Flag abgeschaltet werden

Meine Idee wäre, einen neuen API-Endpoint für die Registrierung zu bauen, der über einen Key geschützt ist. Gegen diesen Endpunkt kann sich die Plesk-Extension registrieren (als Mailadresse dann vielleicht sowas wie siwecos@$reversednsdesservers.com, Passwort wird lokal in der Extension gespeichert) und bekommt darüber das API Token.

Meinungen?
@Lednerb @Skeeve 

LG
David

**Comment by Skeeve** [comment]
Hi
Meine Meinung zu


  1.  keine Notifications oder Recurrent Scans - beides läuft direkt über Plesk, könnte dann in Abhängigkeit vom DB-Flag abgeschaltet werden

Recurrent Scans sollten dann aber bei uns gegebenenfalls ablehnbar sein, falls sie zu häufig kommen. Wir scannen jede Domain einmal am Tag. Öfter sollten die das auch nicht dürfen, oder?

Stephan Hradek
Senior Software Entwickler. SIWECOS
------------------------------
eco - Verband der Internetwirtschaft e.V.
Lichtstraße 43h
50825 Köln
Fon: +49 221 - 70 00 48 – 146
Fax: +49 221 - 70 00 48 – 111
Mobile: +49 175 - 49 79 209
E-Mail: stephan.hradek@eco.de<mailto:stephan.hradek@eco.de>
Web: https://www.eco.de

Wir gestalten das Internet. Heute. Gestern. Über Morgen.

------------------------------
eco – Verband der Internetwirtschaft e.V.
Hauptgeschäftsführer: Harald A. Summa
Geschäftsführer: Alexander Rabe
Vorstand: Oliver Süme (Vorsitzender), Klaus Landefeld (stv. Vorsitzender), Felix Höger, Prof. Dr. Norbert Pohlmann
Vereinsregister: Amtsgericht Köln, VR 14478
Sitz des Vereins: Köln


Am 19.02.2019 um 09:11 schrieb David Jardin <notifications@github.com<mailto:notifications@github.com>>:


Servus Zusammen,

wir haben eine Anfrage von Plesk, die wollen eine SIWECOS-Extension für ihre Plattform bauen und haben hierbei ein paar abweichende Wünsche für das Verhalten der API:

  1.  automatische Registrierung: damit der Nutzer nach der Installation der Extension keine manuellen Aktionen mehr vornehmen muss, soll die Registrierung eines Benutzeraccounts automatisiert werden. Das würde bedeuten:

  *   kein Captcha
  *   kein Double-Opt-In
  *   Flag in der DB dass das ein Service-Account ist

  1.  keine Notifications oder Recurrent Scans - beides läuft direkt über Plesk, könnte dann in Abhängigkeit vom DB-Flag abgeschaltet werden

Meine Idee wäre, einen neuen API-Endpoint für die Registrierung zu bauen, der über einen Key geschützt ist. Gegen diesen Endpunkt kann sich die Plesk-Extension registrieren (als Mailadresse dann vielleicht sowas wie siwecos@$reversednsdesservers.com<mailto:siwecos@$reversednsdesservers.com>, Passwort wird lokal in der Extension gespeichert) und bekommt darüber das API Token.

Meinungen?
@Lednerb<https://github.com/Lednerb> @Skeeve<https://github.com/Skeeve>

LG
David

**Comment by Lednerb** [comment]
Hallo David,


ich sehe hier grundsätzlich 2 Varianten zur Realisierung:

**Variante 1: CA nutzen, eigene Business-Layer-Geschichte bauen**

Sobald CA und BLA sauber voneinander getrennt sind, könnte ein Drittanbieter sich eine Umgebung mit CA und Scanner einfach selbst hosten, von der CA dann die Ergebnisse bekommen.

Vorteil:
- maximale Flexibilität im Umgang mit den Ergebnissen etc.

Nachteile:
- Arbeitsaufwand
- Infrastrukur muss bereitgestellt und skaliert werden

------------------

**Variante 2: SIWECOS Nutzen als 3rd-Party-Integration**

Es wäre auch möglich dann in der BLA ein Token mit bestimmten Rechten und Einstellungen anzulegen sodass bspw. die recurrent scans deaktiviert wurden und dieses Plesk-Token dann einfach die Domains anlegen darf.

Vorteile:
- Kein großer Aufwand zur Integration
- SIWECOS-Infrastruktur wird genutzt

Nachteile:
- SIWECOS-Infrastruktur wird genutzt

Wir sollten unbedingt beachten, dass wenn so eine große Integration ansteht, auch die SIWECOS-Infrastruktur das aushalten muss.

-------------------

**Variante 3: Eigenes Plugin mit Token**
Ähnlich zur WP-Integration usw. könnte ein angepasstes Plugin auch die Aufgaben übernehmen in Verbindung mit dem angepassten Token aus Nummer 1, sodass die Freischaltung direkt erfolgt.

Ob es dann aber Sinn macht, keine `recurrent` Scans auszuführen ist fraglich, weil dann ja auch die Siegel-Generierung etc. nicht genutzt werden kann.

Vorteile:
- Partnerschaft / Kooperation Plesk & SIWECOS
- Einfache Integration
- Werbung und Nutzen für beide Seiten

Nachteile:
- SIWECOS-Infrastruktur wird genutzt und muss da mit skalieren


Variante 3 müsste deiner Vorstellung am ehesten entsprechen.

**Comment by SniperSister** [comment]
>  **Variante 1: CA nutzen, eigene Business-Layer-Geschichte bauen**

Ist raus, wir wollen ja mehr Nutzer für unsere Plattform begeistern und nicht Parallelplattformen bauen :)

> **Variante 2: SIWECOS Nutzen als 3rd-Party-Integration**

Das wäre meine Wunschvariante. Dadurch dass die Integration über eine Plesk Extension passiert, ist hier auch nicht zu erwarten dass auf einen Schlag tausende Domains hinzu kommen

> **Variante 3: Eigenes Plugin mit Token**

Kannst du das nochmal genauer erklären?

**Comment by Lednerb** [comment]
>> **Variante 3: Eigenes Plugin mit Token**
>
>Kannst du das nochmal genauer erklären?

Hier stelle ich mir vor, dass ein Plugin / Extension in Plesk integriert wird, die die Domains in der BLA registriert, die Scans dann genau so wie auf der SIWECOS-Seite ausgeführt werden, der aktuelle Report einsehbar ist und das SIWECOS-Siegel zur Einbindung anzeigt.

Als Besitzer bzw. User wird dann für jede Plesk-Instanz ein neuer Nutzer angelegt bzw. optional dann die Möglichkeit, sich in dem Plugin mit den ggf. vorhandenen SIWECOS-Nutzerdaten einzuloggen.

Es wird also im Unterschied zu Variante 2 nicht global in Plesk ein User-Token angelegt und automatisch auf jeder Plesk-Instanz mit SIWECOS verbunden, sondern eine Extension installiert, die dann diesen einen Nutzer und all seine Domains verwaltet.

Innerhalb von Plesk könnte dann auch eine Art Domain-Verifizierung erfolgen, indem einfach in einer URL das jeweilige SIWECOS-Token angezeigt wird. Bspw: `https://plesk.example.org/siwecos/verify/www.meine-tolle-webseite.de` oder aber einfacher, dass Plesk die Token-Verifizierung direkt übernimmt und dann unter `https://meine-tolle-webseite.de/siwecos_token.html` die Seite anlegt.


---------------------------

Kurzum: Ich denke wir preferieren die gleiche Option.
Variante 2 wäre einmal ein globales Plesk Token mit einer direkten Integration in Plesk für alle Installationen (ziemlich heftig).
Variante 3 ist, dass jede Plesk-Installation per Extension SIWECOS einbinden kann und jede Instanz ein eigenes Token erhält.

----------------------------

Variante 3 macht aber eig. auch nur mit reccurent Scans einen Sinn und kann dann direkt auch den Code zum Anzeigen der Siegel bereitstellen.

**Comment by Lednerb** [comment]
Zusätzlich würde dann auch das Credit-System Sinn ergeben und ggf. für den Mehraufwand für das Scannen von großen Instanzen (viele Domains mit Plesk verwaltet) eine Monetarisierung ins Spiel kommen, um SIWECOS weiter betreiben zu können und die Ressourcen nicht zu überstrapazieren.

**Comment by SniperSister** [comment]
> Als Besitzer bzw. User wird dann für jede Plesk-Instanz ein neuer Nutzer angelegt

Und genau hier wird’s spannend: aktuell ist unser Registration endpoint hier nicht für Automatisierung geeignet, weil er per captcha gesichert und als opt-in programmiert ist - daher brauchen wir imho einen weiteren endpoint?

**Comment by Lednerb** [comment]
Das ist korrekt.

Wir hätten dann die Unterscheidung zwischen `User`, ein Nutzer der die SIWECOS-Webapp direkt nutzt und mit Namen etc. angelegt werden kann, dann auch E-Mails bekommt usw. und reinen `Token`-Nutzern, die sich nicht in die SIWECOS-Webapp einloggen können, lediglich das Token bekannt ist und die dazugehörigen Domains.

Domains müssen dann aber verifiziert sein.
Ein Einloggen in die Webapp ist später dann mit den bereits registrierten Domains nicht möglich (es sei denn, sie werden umgezogen, wobei wir diesen Use-Case bisher noch nicht integriert haben, oder?)

**Comment by Lednerb** [comment]
Siehe oben: (https://github.com/SIWECOS/siwecos-business-layer/issues/100#issuecomment-466629707)

Alle Punkte sind soweit umgesetzt. Ein Token kann direkt registriert und genutzt werden, ohne dass es einen dazugehörigen `User` gibt. Doku folgt.

**Comment by Lednerb** [comment]
Doku siehe hier: https://siwecos.github.io/siwecos-business-layer/#tokens

**Comment by Lednerb** [comment]
@SniperSister Die Dokumentation wurde aktualisiert, es ist notwendig, die AGB zu akzeptieren (#132)
