### ISSUE TITLE
Siegel werden nicht generiert.

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-business-layer#101]
Seit dem 13.2. (spätestens) sollten Siegel nach jedem not-freescan generiert werden. Es sind bisher aber erst knapp 70 Siegel vorhanden und es wurden selten mehr als 10 am Tag erstellt. Es sollten aber pro Tag > 3000 erstellt werden und es sollten nur Siegel von heute und gestern (außer abgemeldeter Domains) vorhanden sein. Tatsächlich sieht der momentane Stand so aus:

          '2019-02-13' => 10
          '2019-02-14' => 7,
          '2019-02-15' => 6,
          '2019-02-16' => 7,
          '2019-02-17' => 2,
          '2019-02-18' => 2,
          '2019-02-19' => 4,
          '2019-02-20' => 2,
          '2019-02-21' => 2,
          '2019-02-22' => 16,
          '2019-02-23' => 5,
          '2019-02-24' => 4,

**Comment by Lednerb** [comment]
Behoben, lag an zu altem Cron Deployment ohne korrekter Callback-URL.
