### ISSUE TITLE
Scanner Sortieren für webapp, freeapp und Reports

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-business-layer#117]
Damit die Scanner immer in derselben Reihenfolge angezeigt werden, sollte der business layer die Scanner immer in derselben Reihenfolge ausgeben.

Um das sicherzustellen, sollten die Scannerergebnisse sortiert sein.

Die Testergebnisse sortieren wir nicht, für V2 legen wir fest (in die Doku aufnehmen!), dass die Scanner selbst ihre Ergebnisse immer in konsistent derselben Reihenfolge liefern.

**Comment by Lednerb** [comment]
Ich verschiebe diesen Punkt doch in die Core-Api.

Grund:
Wenn weitere Scanner hinzukommen, muss dies nicht in der BLA, sondern in der CA konfiguriert werden.

Wenn ein Nutzer lediglich die CA einsetzt, sich eine eigene BLA baut, wäre es trotzdem schön, wenn die Ergebnisse in einer sortieren Folge erscheinen.

Ist das Problem in der CA gelöst und für alle zukünftigen Scanner somit ebenfalls angepasst, ist das Problem auch gleichzeitig in der BLA, webapp, freeapp, evtl. Plugins und Reports gelöst.
