### ISSUE TITLE
errorMessage mit Exception-Text?

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/siwecos-business-layer#119]
Beim Scan mit Connection Error wird einfalsches Format ausgegeben:

```
{
    "name": "CMSVERSION",
    "version": "1.0.0",
    "hasError": true,
    "errorMessage": "cURL error 28: Resolving timed out after 5516 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)",
    "score": 0,
    "id": 3
  }
```

`errorMessage` muss vom Typ [TranslatableMessage](https://github.com/SIWECOS/siwecos-core-api/tree/ff946d3b1e7a50ce072a6a0c0d1324f6e4dd75e6#translatablemessage-object) sein, um dem Standard zu entsprechen.

**Comment by Skeeve** [comment]
"Momentan sehe ich keinen Mehrwert für KMUs darin, bspw. einen englischsprachrigen curl-Fehler auszugeben"
Jein. Einige der Curl Fehlermeldungen könnten hilfreich sein: z.B. Nr. 7, 8, 9, 22, 28, 35(?), 47, 52, 60 https://curl.haxx.se/libcurl/c/libcurl-errors.html

Wenn man die abfängt und dem Kunden mitteilt (z.B. für 60) "Ihr Server hat ein ungültiges SSL Zertifikat geliefert", könnte das in der Fehlersuche hilfreich sein.

Ein MUSS das zu liefern sollte es aber nicht geben.

**Comment by SniperSister** [comment]
Spricht was dagegen es vom Scanner returnen zu lassen, dann aber in der BLA den Placeholder zu ignorieren? Der Scanner kann somit im Standalone sinnvolles Feedback geben.

**Comment by Skeeve** [comment]
Placeholder dürfen auch ignoriert werden.

**Comment by Lednerb** [comment]
> Spricht was dagegen es vom Scanner returnen zu lassen, dann aber in der BLA den Placeholder zu ignorieren? Der Scanner kann somit im Standalone sinnvolles Feedback geben.

Das funktioniert, setzt aber voraus, dass der genutzte Placeholder dann nicht im Text verwendet wird.
Insofern eine sehr gute Lösung, die ich auch befürworten würde.

Also konkretes Beispiel:

Nachricht:
```
"errorMessage": {
    "translationStringId": "INTERNAL_ERROR_OCCURED",
    "placeholders": {
      "EXCEPTION_MESSAGE": "cURL error 28: Resolving timed out after 5517 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)"
    }
  },
```

`INTERNAL_ERROR_OCCURED`: Ihre Seite konnte nicht gescannt werden.

(Nachricht **ohne** `:EXCEPTION_MESSAGE`)
