### ISSUE TITLE
How can we change the activation mail?

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-business-layer#12]
Activation mail says

>    Diese Email wurde automatisch vom SIWECOS System zur Überprüfung Ihrer Domain generiert.

But it's not the DOMAIN, it's the mail address.

Instead of fixing, please tell us how to fix ourselfs.

**Comment by SniperSister** [comment]
See resources/views/mail/registration.blade.php

**Comment by Skeeve** [comment]
Thanks a lot
