### ISSUE TITLE
Curl-Error beim Validieren einer Domain

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-business-layer#120]
Wir sollten Kunden auf Zertifikatsfehler beim Validieren einer Domain hinweisen statt die Domain nur abzuweisen. Abweisen ist in Ordnung, bisher weiß der Nutzer aber nicht, warum abgewiesen wurde.

Siehe auch: #121

**Comment by Lednerb** [comment]
Alle interessanten Fehlermeldungen auflisten

**Comment by Skeeve** [comment]
* CURLE_UNSUPPORTED_PROTOCOL (1)

The URL you passed to libcurl used a protocol that this libcurl does not support. The support might be a compile-time option that you didn't use, it can be a misspelled protocol string or just a protocol libcurl has no code for.

* CURLE_URL_MALFORMAT (3)

The URL was not properly formatted.

* CURLE_COULDNT_RESOLVE_HOST (6)

Couldn't resolve host. The given remote host was not resolved.

* CURLE_COULDNT_CONNECT (7)

Failed to connect() to host or proxy.

* CURLE_REMOTE_ACCESS_DENIED (9)

We were denied access to the resource given in the URL.

* CURLE_HTTP2 (16) - Generischer Fehler - Vielleicht auch nichts ums dem Nutzer zu melden

A problem was detected in the HTTP2 framing layer. This is somewhat generic and can be one out of several problems, see the error buffer for details.

* CURLE_PARTIAL_FILE (18)

A file transfer was shorter or larger than expected. This happens when the server first reports an expected transfer size, and then delivers data that doesn't match the previously given size.

* CURLE_HTTP_RETURNED_ERROR (22)

This is returned if CURLOPT_FAILONERROR is set TRUE and the HTTP server returns an error code that is >= 400.

* CURLE_OPERATION_TIMEDOUT (28)

Operation timeout. The specified time-out period was reached according to the conditions.

* CURLE_SSL_CONNECT_ERROR (35)

A problem occurred somewhere in the SSL/TLS handshake. You really want the error buffer and read the message there as it pinpoints the problem slightly more. Could be certificates (file formats, paths, permissions), passwords, and others.

* CURLE_TOO_MANY_REDIRECTS (47)

Too many redirects. When following redirects, libcurl hit the maximum amount. Set your limit with CURLOPT_MAXREDIRS.

* CURLE_GOT_NOTHING (52)

Nothing was returned from the server, and under the circumstances, getting nothing is considered an error.

* CURLE_SEND_ERROR (55) - nicht sicher ob's relevant ist

Failed sending network data.

* CURLE_RECV_ERROR (56) - nicht sicher ob's relevant ist

Failure with receiving network data.

* CURLE_SSL_CIPHER (59) - nicht sicher ob's relevant ist

Couldn't use specified cipher.

* CURLE_PEER_FAILED_VERIFICATION (60)

The remote server's SSL certificate or SSH md5 fingerprint was deemed not OK. This error code has been unified with CURLE_SSL_CACERT since 7.62.0. Its previous value was 51.

* CURLE_BAD_CONTENT_ENCODING (61)

Unrecognized transfer encoding.

**Comment by Lednerb** [comment]
Problem: Es wird Guzzle genutzt, nicht curl direkt.

Wir können die verschiedenen [Guzzle Exceptions](http://docs.guzzlephp.org/en/latest/quickstart.html#exceptions) abfangen und je Exception eine enstprechende Fehlermeldung ausgeben oder einfach direkt implementieren:

"Beim Validieren Ihrer Domain ist folgender Fehler aufgetaucht: GUZZLE_EXCEPTION_MESSAGE"

Der erste Teil wäre dann die Reaktion des Frontends, die BLA würde lediglich die Exception message ausgeben.

**Comment by Skeeve** [comment]
Direkt die Exception auszugeben halte ich für nicht so sehr hilfreich. Leider sind die Fehler für Guzzle nicht so ausführlich beschrieben, wie bei curl. Ich kann bei den Guzzle Beschreibungen z.B. nicht feststellen, welcher Fehler bei einem Zertifikatsproblem erscheint.
