### ISSUE TITLE
Userhilfen bei Domainvalidierung verbessern

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-business-layer#121]
Die Idee hier ist, dem User mehr Informationen zu geben, warum seine Domainvalidierung fehlgeschlagen ist:, z.B.

1. Text z.B.: "**Unter der URL (**_Hier die URL der Domain angeben, wie sie nach allen Redirects war_**) wurde Folgendes gefunden (**_Auszug aus seiner index.html oder was immer kam_**). Es fehlt das siwecostoken.**"
1. "**Unter der URL (**_Url der Tokendatei_**) wurde keine Datei gefunden / wurde diese Datei gefunden (**_Auzug aus der gefundenen Datei_**)**"

**Comment by Lednerb** [comment]
Einzig der Alternativ-Vorschlag macht für unsere Zielgruppe Sinn, da die Auszüge recht lang werden können.

Wäre die Reaktion des Frontends auf HTTP-Fehlercode `410`:
https://siwecos.github.io/siwecos-business-layer/#domain-verification

Dieser Fehlercode sollte nur ausgegeben werden, wenn Verbindungsfehler nach #120 ausgeschlossen wurden. Bei Fehlern nach #120 wird demnächst der HTTP-Fehlercode `409` zurückgegeben.
