### ISSUE TITLE
Please evaluate using gettext / .mo files

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-business-layer#13]
According to https://en.wikipedia.org/wiki/Gettext#Implementations it should be possible to use gettext file (.mo) in php.

As I already implemented a script for converting our current translations directory into a .pot file, which we will use for translations, it might be a good thing to make use of them as well in BLA. Please check whether or not this is feasable.

Please note that due to the fact that some "msgid"s (i.e. untranslated texts) are identical for different contexts, I used the placeholder as a (msgctxt) message context. This might be an issue.

It also might be an issue, that the …_SOLUTION_TIPS placeholders should be able to contain wikitext links.

If it's not feasable we will have to create a script to convert .po files into siwecos.php files.

**Comment by SniperSister** [comment]
Stupid question: why is there such a strong need for .po in the project? I haven’t used po a single time in the last ten years and never ran into any issues.

**Comment by Skeeve** [comment]
If you have another idea how to give a non-Programmer a program file with texts to translate, please share your ideas.

We do not want to rely on translators to understand the syntax of a .vue, .json or .php file. 

So one valid approach is to use a .po file which can be handled by (e.g.) poedit which (hopefully) non-programmers are comfortable with.

Current idea is to convert the .po file into our (currently) required target format. But if .php can handle the resulting files itself, there might be no need for conversion . That's why I opened this issue after discussing with Marcel.

**Comment by Weegy** [comment]
It is possible to use PO files with Larvel. See Package laravel/gettext. Please make a final decision about the usage before implementing it.

**Comment by Weegy** [comment]
Is this still an issue?

**Comment by Skeeve** [comment]
We will stick to siwecos.php
