### ISSUE TITLE
IDN Domains

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-business-layer#131]
Mindesten das Siegel hat Momentan Probleme mit "Umlautdomains". Werden sie als punycode eingetragen, sollte alles in Ordnung sein.

Allerdings erlauben wir die Eintragung auch mit Umlauten. Hier muß also mindestens beim Siegel nachgebessert werden.

**Comment by Lednerb** [comment]
IDN Domains lassen sich registrieren.
Die Siegel können ebenfalls angelegt werden.

Zu beachten wäre ausschließlich, dass es ein Dateisystem-Fehler geben kann, wenn eine Domain registriert wird, die für ein Filesystem unzulässige Zeichen enthält.

Das sollte soweit jedoch nicht eintreten.
Anpassung falls in der Zukunft dennoch Fehler auftreten sollten.
