### ISSUE TITLE
AGB Flag sicherstellen

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-business-layer#132]
Auch wenn das AGB Flag nicht gespeichert werden sollte (Legal ist gefragt), muß sichergestellt sein, dass die API einen Eintrag nur dann speichert, wenn das AGB Flag im Request gesetzt ist.

**Comment by Lednerb** [comment]
`agb_check` ist nun `required`.

Es ist nicht möglich, sich ohne `"agb_check": true` als Nutzer zu registrieren.
Es ist nicht möglich, ohne senden von `"agb_check": true` ein Token für den externen Einsatz zu generieren.

Somit entspricht das jeweilige `created_at` Datum exakt dem Zeitpunkt der Registrierung und damit ebenfalls dem Zeitpunkt der Akzeptanz der AGB.
