### ISSUE TITLE
Recurrent Scans mit Timeout markieren und benachrichtigen

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-business-layer#137]
### Edit by @Lednerb:

Siehe aktueller Plan: https://github.com/SIWECOS/siwecos-business-layer/issues/137#issuecomment-524287960

-----------------------

Es gibt Scans, z.B. scan_result id 1395527, bei denen der Scanner in einen timeout lief, has_error ist aber auf false.

Sollte das nicht "true" sein?

**Comment by Lednerb** [comment]
## Folgende Änderung:

Sollte ein Scan seit 6 Stunden von seinem `updated_at` immernoch den Status `running` haben, dann als `failed` markieren und technical support per Mail benachrichtigen.

**Comment by Lednerb** [comment]
Eingebaut.

Es gibt einen Parameter in den Einstellungen, um die Zeitspanne zu definieren, nach deren Ablauf der Scan als `failed` markiert wird und eine Mail versandt wird.
