### ISSUE TITLE
Which placeholders can be used in mails to users?

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-business-layer#14]
We are especially interested in placeholders for the user's name, salutation and email address.

But every other placeholder which can be used would be good to know as well.

**Comment by Weegy** [comment]
We can use any user / domain information we want

**Comment by Skeeve** [comment]
Great, so how do we put name, salutation and email into the text?

**Comment by Weegy** [comment]
Just give me a text with some placeholder and I will do the rest for you as an example

**Comment by Skeeve** [comment]
Will ask Tom to provide this information.

As far as I know we already had placeholders in the previous version, so it should be easy for him and it will be more consistant that way.

**Comment by Skeeve** [comment]
These placeholders would be nice:

placeholder | content
---|---
email | for the mailaddress
name | for last name
vorname | for given name
given_name | as well for given_name
anrede | for the german salutazion
salutation | for the english one

**Comment by Skeeve** [comment]
I did it myself - not as nice as requested, but after understanding (part of) the templating system, I think we can live with what we hae now.
