### ISSUE TITLE
Proposal for receiving new credits

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-business-layer#15]
After discussion with Peter: Every account will receive up to 50 free credits per day.

So when an account has 10 validated domains, he will be down to 40 after the automatic scans. But there should be an automatism to update the credits to 50 once per day.

Question remains what to do once we allow users to pay for credits.

My proposal is:

1. accounts having below 50 credits will be set to 50 once per day
2. account having more than 50 credits will receive one free credit per validated domain once per day.

The second adjustment is required so that the automatic, daily scans are not reducing the payed amount of credits.

It's unclear to me where this automatism has to be implements. Currently it's said that we have an automatic scan done every night at 01:00 (but I cannot see that in the database) and maybe it's a good idea to implement the logic at the same place.

**Comment by Weegy** [comment]
All token with credit below 50 will be restocked at 00:00
