### ISSUE TITLE
PDF Download nicht mit Token in der URL

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-business-layer#154]
Szenario: Kunde gibt Link zu seinem PDF Report weiter.

In der URL steckt das Token mit dem jeder als dieser User agieren kann.

**Comment by Lednerb** [comment]
@SniperSister 

also müssen wir hier auf einen POST-Request umschalten, der dann das PDF als Report zurückliefert.

Sonstige Ideen?

**Comment by SniperSister** [comment]
> also müssen wir hier auf einen POST-Request umschalten, der dann das PDF als Report zurückliefert.

Indeed

> Sonstige Ideen?

One-Time-Tokens spezifisch für die PDFs, aber das ist natürlich der Overkill

**Comment by Lednerb** [comment]
Ok, nehmen wir Nummer 1, ich schicke gleich ein Update.

**Comment by Lednerb** [comment]
Done. See PR #155
