### ISSUE TITLE
Seems test details cannot be blended in

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-business-layer#16]
According to https://github.com/SIWECOS/InfoLeak-Scanner/blob/master/doc/InfoLeak_Placeholders.txt it seems {something} is the expected notation for testdetails.

Unfortunately they are not replaced.

So I receive

    Verwendete CMS {cms} detektiert.

instead of the expected

    Verwendete CMS Wordpress detektiert.

**Comment by Weegy** [comment]
Big questions now, where are the replacements for the placeholder? Are they transfered via the callback?

**Comment by Skeeve** [comment]
@Weegy I hoped, @ic0ns and you discussed.

My understanding is - and it might not be completely correct - is as follows:

Example

```JSON
{
  "name": "JS_LIB",
  […] 
  "scoreType": "warning",
  "testDetails": [{
    "placeholder": "JS_LIB_ONLY",
    "values": {
      "js_lib_name": "jquery",
      "node": "defer",
      "node_content": "defer"
    }
  }]
}
```

The "testdetails" contain an array of objects.

Each object defines a "placeholder".

The text for the placeholder can be found in siwecos.php.

The text of the placeholder can contain other placeholders (like "cms" above or "js_lib_name" in the example code). whose values are defined in the "values" object of the testdetails array elements.

So JS_LIB_ONLY could have a text defined in siwecos.php which reads

> We found the javascript library %js_lib_name% in %node%.
