### ISSUE TITLE
Bessere Verifizierungs Rückmeldung

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-business-layer#160]
Wir brauchen bessere Meldungen an die Nutzer, wenn eine Verifizierung einer Domain fehlschlägt.

Siehe #159 

Wenn hier die Meldung "Ihre Domain XXX gewährt uns keinen Zugriff. Die Meldung war: 403 Forbidden" erschienen wäre, hätten wir schneller die Ursache finden können.

**Comment by Lednerb** [comment]
Bereits realisiert:

https://github.com/SIWECOS/siwecos-business-layer/blob/d5381d625e2ece73dd674867cc16d74f9416db22/app/DomainVerifier.php#L26-L38


Siehe Kibana Logging -> gespeicherte Suche: "Domain-Validierungsfehler"

**Comment by Skeeve** [comment]
Leider nicht realisiert.

Der Nutzer hat seinen 403 nicht gesehen, weil Du keine Exception wirfst sondern 'false' zurückgibst.

https://github.com/SIWECOS/siwecos-business-layer/blob/d5381d625e2ece73dd674867cc16d74f9416db22/app/DomainVerifier.php#L45-L53

**Comment by Lednerb** [comment]
Im oben genannten Fall hätte der Nutzer allerdings auch mit der 403er Nachricht nichts anfangen können.

"Bereits realisiert" war auf das __wir__ bezogen:

> Wenn hier die Meldung "Ihre Domain XXX gewährt uns keinen Zugriff. Die Meldung war: 403 Forbidden" erschienen wäre, hätten wir schneller die Ursache finden können.
