### ISSUE TITLE
Anpassung Domain mainUrl auf Crawler-Ergebnis / sonst http

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-business-layer#163]
Es geht um die Domains mit domain id 1685 und 1686 in der Prod DB.

> seit geraumer Zeit bemerke ich, dass der Sicherheitsbericht von zwei meiner registrierten Websites […] nicht abgerufen werden kann. Ich bekomme stattdessen die Fehlermeldung "Fehler beim Abruf der Scan-Ergebnisse, bitte versuchen Sie es später erneut". Erneute Versuche führen aber zum gleichen Ergebnis.
>
> Diese beiden Seiten haben keine Transportverschlüsselung (HTTPS), werden jedoch in der Übersicht als solche geführt. Der Versuch, sie ohne Transportverschlüsselung hinzuzufügen, schlägt ebenfalls fehl. Da gibt es die Fehlermeldung "Die Domain konnte nicht hinzugefügt werden, bitte versuchen Sie es später erneut".
>
> Jetzt wüsste ich doch gerne, wie sich die Sache beheben lässt, sodass die Seiten wieder regelmäßig geprüft werden und ich den Sicherheitsbericht einsehen kann.

**Comment by Skeeve** [comment]
Ein weiterer Fall ist aufgetreten. Siehe bitte die Support Mails.

**Comment by Skeeve** [comment]
Nachtrag: Gescannt wird. Die Scans haben aber ERROR auf true. Vermutlich u.a. weil TLS ERROR auf true hat.

**Comment by Lednerb** [comment]
Wir Scannen keine nicht-https Seiten. Diese übertragen Daten unverschlüsselt und sind somit ohnehin als "unsicher" zu Kennzeichnen.

Es müsste allerdings in der Tat ein Ergebnis, zumindest ein Hinweis angezeigt werden, warum die Scans nicht abgerufen werden können.

Für die Reports werden momentan lediglich nicht-fehlgeschlagene Scans ausgegeben.
Dies wurde eingebaut, um ein drop des Scores zu verhindern, sofern lediglich ein Scanner ein Problem meldete.

Muss weiter evaluiert werden, wie wir hier am besten vorgehen können.

**Comment by Skeeve** [comment]
Bisher hatten wir sie gescannt. Wir sollten das auch weiterhin machen.

Vorschlag:
Maximalscore kann bei nur-https mximal 50% erreichen

Frage: Wieviele der registrierten Domains sind nur-https?

**Comment by Skeeve** [comment]
Blöd ist auch: Die Siegel der sites werden angezeigt. Ein Klick aufs Siegel führt aber zur Zertifikatsseite die da behauptet, wir scannen nicht.

**Comment by Lednerb** [comment]
> Blöd ist auch: Die Siegel der sites werden angezeigt. Ein Klick aufs Siegel führt aber zur Zertifikatsseite die da behauptet, wir scannen nicht.

Irrelevant, da niemand das Siegel in die Seite einbinden wird, wenn er keine Scans durchführen kann.

**Comment by Lednerb** [comment]
> Bisher hatten wir sie gescannt. Wir sollten das auch weiterhin machen.

Seit `v2` nicht mehr, vorher nur, da wir URLs anstatt Domain registriert hatten.

Andernfalls müssten wir vor einem Scan-Start prüfen, welches Protokoll verfügbar ist oder jeweils mit der `http` Variante starten und dann, sofern die Seite korrekt eingerichtet ist, automatisch die `https` Variante Scannen.

Wird aber bei fehlenden Redirects direkt zu einem starken score drop führen.

**Comment by Lednerb** [comment]
> Frage: Wieviele der registrierten Domains sind nicht-https?

Adhoc nicht ermittelbar.

**Comment by Skeeve** [comment]
> Irrelevant, da niemand das Siegel in die Seite einbinden wird, wenn er keine Scans durchführen kann.
Nein, da bereits registrierte nur-http-Nutzer das Siegel bereits eingebunden haben. Siehe die genannten domain-ids. Den nutzer gibt's schon lange 2019-02-18 19:29:29

> Andernfalls müssten wir vor einem Scan-Start prüfen, welches Protokoll verfügbar ist
Genau so hatte ich die Diskussion damals in Erinnerung: https-Prüfen. Wenn vorhanden okay, wenn nicht mit http weiter.
