### ISSUE TITLE
Reports nach Scanner sortiert, nicht nach URLs/MailDomains

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-business-layer#165]
Für v3 fände ich es praktischer, Ergebnisse würden im Report nach Tests sortiert und erst darin nach URLs. In der momentan (geplanten) Version würden die Testergebnisse unter die gecrawlten URLs sortiert. Letztlich kommt es aber doch darauf an, dass ein identifiziertes Problem gelöst wird. Ich denke, beim Lösen der Probleme wird man nicht zuerst die Probleme einer URL lösen, sondern zuerst ein Problem für alle URLs lösen wollen.

**Comment by Lednerb** [comment]
In Frontend behandelt, schließe daher hier.
