### ISSUE TITLE
Datenbank cleanup / Scans

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/siwecos-business-layer#167]
Um die Datenbank nicht unnötig endlos wachsen zu lassen, sollten wir alte Scans (bspw. älter als 30 Tage) automatisiert löschen lassen.

Die Scans werden ohnehin in elasticsearch zwecks Statisitken und Auswertung gespeichert, in der Datenbank werden diese lediglich für die Ausgabe der Kunden benötigt.

Durch die 30-tägige Speicherung könnte man direkt auf Datenbank-Ebene noch support leisten etc.

Es könnte auch weniger Tage gespeichert werden.

CC: @SniperSister @Skeeve

**Comment by SniperSister** [comment]
Macht sinn!

**Comment by Skeeve** [comment]
Wieviel Platz brauchen wir jetzt? Klingt 90 Tage gut? Damit hat man 1/4 Jahr im direkten DB Zugriff.

Ansonsten von mir aus auch 30 Tage.

**Comment by Lednerb** [comment]
Done by 7042c06
