### ISSUE TITLE
Free Scan should not show results from registered domain runs

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-business-layer#17]
See also #2.

it would be best that a free scan:

1. Does not show cached results from registered scans thus avoiding the issues mentioned here.
2. Should have a delay between reruns of the same domain, avoiding the risk of overloading the target domain. Maybe a minute between each run?

**Comment by Weegy** [comment]
The Problem was, that the DangerLevel were not properly exposed
