### ISSUE TITLE
[prod] Änderng der Mailadresse ohne Bestätigungsmail und ohne Hinweis darauf

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-business-layer#172]
Das Ändern der Mailadresse kann nur erfolgen, wenn man auch ein (neues) Passwort setzt.

Siehe: https://github.com/SIWECOS/webapp/issues/57

Allerdings wird momentan keine Aktivierungsmail dazu verschickt, der Nutzer kann die neue Mailadresse also nicht nutzen.

**Comment by Skeeve** [comment]
Anscheinend funktioniert es in staging aber nicht in prod.

**Comment by Lednerb** [comment]
> Anscheinend funktioniert es in staging aber nicht in prod.

Liegt dann wahrscheinlich an der alten Version und wird dort nicht mehr gefixt.

**Comment by Skeeve** [comment]
Ignorieren wir das Problem da die neue Version ja schon mit den Hufen scharrt… ;)
