### ISSUE TITLE
Es fehlt ein Endpoint für den latest v3 Report

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-business-layer#176]
(Von Sven)

Es gibt folgenden Endpoint: GET /api/v2/domain/{domain}/report/{language?}

Dieser Endpoint gibt mir ohne die Scan_ID den Report, aber nicht den "neuen" aus der v3, mit den zusätzlichen Details

Für den brauche ich die Scan_ID, die ich aber nur bekomme, wenn ich AKTIV auf den Scan-Button klicke

Wenn ich die Seite aber neu lade, "scanne" ich ja nicht direkt, daher kriege ich dann auch diese Zusat-Details nicht

Mit anderen Worten: in der v3 fehlt ein Endpoint für den letzten scan

POST /api/v2/siwecosScan/{scan_id}/{language_code

hier müßte es noch sowas geeben wie

POST /api/v2/siwecosDomainScan/{domain}/{language_code

Analog für PDF

**Comment by sven-ahrens** [comment]
Genau, also prinzipiell bräuchte ich einen Endpoint, der mir für eine Domain die letzte bzw. neuste Scan-Id zurückgibt, woraufhin ich mir dann den Report aus der v3 fetchen kann.

**Comment by sven-ahrens** [comment]
Wie in dem Ticket hier schon beschrieben bzw. zitiert habe wir ansonsten das Problem, dass man jedes mal erst auf den Scan-Button klicken müsste, um dann die Scan-Id zu bekommen, um dann wiederum den neuen Report aus der v3 fetchen zu können.

Wenn ich die Seite neu lade oder erst gerade drauf komme, scanne ich aber ja nichts und dementsprechend kann ich nur den "alten" Report aus der v2 über ``GET /api/v2/domain/{domain}/report/{language?}``fetchen

**Comment by Skeeve** [comment]
Ich denke, mein letzter PR hat das Problem gelöst. Es gibt jetzt

`https://api.staging.siwecos.de/api/v2/latestSiwecosScan/{domain}/{language}`

**Comment by Lednerb** [comment]
@sven-ahrens der Endpoint ist nun wie folgt implementiert:

https://siwecos.github.io/siwecos-business-layer/#retrieving-the-latest-full-scan-report
