### ISSUE TITLE
Additional accounts

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-business-layer#18]
We think it might be a good idea to have additional accounts for a domain. Maybe with restricted access (just view, not starting scans or registring/deleting domains).

Reasoning: When a user wants his service provider to fix the issues found by siwecos, it would be good the service provider could actually see what siwecos reports. As we do not have PDF (yet), it might be a good option to allow the service provider to log in and check without having to give them the user's credentals.

If this is too much overhead another idea could be to allow domain owners to give other registered users read access.

That way a service provider can register one account and will be able to see each domain he was granted access for.

Advantage would be: A Service Provider just needs to have one account and can manage multiple customers. Idea is similar to "public key autentication" in ssh: The domain owner simply ads one (or more) account names into a list of allowed viewers per domain.

**Comment by Weegy** [comment]
Both options are not really trivial.

**Comment by Lednerb** [comment]
Nun realisierbar.

Eventuell ebenfalls die Option integrieren, einen bestimmten Scan-Report über secret-URL zu teilen.

Wenn ein Hoster / Admin / Service-Provider die Seite eines Kunden absichern möchte, braucht dieser auch die notwendigen Rechte, um einen Scan manuell starten zu können.

Daher wäre der mehrfache Zugriff auf eine Domain am sinnvollsten umzusetzen.
Dies wäre nun relativ einfach umsetzbar, indem die `Domain` einem weiteren `Token` zugewiesen wird.

Problematisch wäre die Credits-Verteilung bei Domain-Start: Von welchem Token soll der Scan-Start berechnet werden?

Auch zu berücksichtigen: Der Provider könnte auch einfach lokal seine Scan-Instanz betreiben, via [docker-compose-scanners](https://github.com/SIWECOS/docker-compose-scanners) und bräuchte dann maximal Lesezugriff, was auch über secret-Domains ausreichend sein könnte.

Ist die Seite erst einmal relativ "sicher" konfiguriert, so wird sich daran nicht alle 24 Stunden was ändern. Der Kunde kann bei Bedarf wiederum den Provider kontaktieren...

**Comment by Skeeve** [comment]
Das sollten wir uns zusammen genauer ansehen. Bisher war eine Domain über token-id immer genau einem token und jedes Token genau einem User zugeordnet. Ich weiß nicht, wie Du das jetzt implementiert hast.

**Comment by Lednerb** [comment]
> Das sollten wir uns zusammen genauer ansehen. Bisher war eine Domain über token-id immer genau einem token und jedes Token genau einem User zugeordnet. Ich weiß nicht, wie Du das jetzt implementiert hast.

Ein Nutzer hat zwangsläufig ein Token; ein Token braucht hingegen nicht zwangsläuig einen Nutzer.
Jede Domain wird aktuell genau einem Token zugeordnet (evtl. zukünftig dann einem oder mehreren).
Jeder Scan ist einer Domain zugeordnet.

**Comment by Lednerb** [comment]
Machbar, sofern eine Domain mehreren Tokens zugeordnet werden kann.

**Comment by Lednerb** [comment]
Nicht leicht realisierbar. Zu aufwendig und mit zu begrenztem Nutzen.
Daher vorerst auf Eis gelegt.

**Comment by Skeeve** [comment]
Mit dem momentanen Datenmodell nicht umsetzbar. Mit dem alten hätte es geklappt.
