### ISSUE TITLE
http statt https im Report?

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-business-layer#181]
Bitte mal testen.In Staging (und angeblich auch in Production) wird als Protokoll für "www.webmasting.de" immer http statt https angezeigt. Ein Test mit curl zeigt mir aber, dass ein 301 mit https zurückgegeben wird.

```
Skeeve@s-scanner:~$ curl -v http://www.webmasting.de
* Rebuilt URL to: http://www.webmasting.de/
*   Trying 83.138.86.74...
* TCP_NODELAY set
* Connected to www.webmasting.de (83.138.86.74) port 80 (#0)
> GET / HTTP/1.1
> Host: www.webmasting.de
> User-Agent: curl/7.52.1
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Date: Mon, 11 Nov 2019 06:46:16 GMT
< Server: Apache/2.4.25 (FreeBSD) OpenSSL/1.0.2k mod_fcgid/2.3.9
< Location: https://www.webmasting.de/
< Content-Length: 234
< Content-Type: text/html; charset=iso-8859-1
<
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://www.webmasting.de/">here</a>.</p>
</body></html>
* Curl_http_done: called premature == 0
* Connection #0 to host www.webmasting.de left intact
```

**Comment by Lednerb** [comment]
#### Log

In `staging` ist die Domain angelegt und verifiziert worden (`2019-11-11 06:34:19`).

Es gibt keine `crawledUrls` oder `mailDomains`; Analyse steht aus.

`->mainUrl`: `http://www.webmasting.de`


------------------------------------

In `production` wird momentan ohnehin noch stets `http://` ausgegeben.

**Comment by Lednerb** [comment]
Folgenden Fehler gab es heute Morgen offenbar:

```
[2019-11-11 06:34:26] staging.CRITICAL: Crawler response could not be processed for domain: {"hasError":["validation.required"],"domain":["validation.required"]}  
```

Der Crawler hätte daher eine Antwort ohne `domain` geschickt.

Evtl. gab es einen zetlich bedingten Ausfall?
Weiter beobachten.

**Comment by Lednerb** [comment]
Server sperrte die SIWECOS IPs, schließe daher hier.
