### ISSUE TITLE
Staging: Unvollständiger Scan für frisch eingetragene Domains?

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-business-layer#182]
Angehängter Report ist für einen Scan, der heute morgen für eine frisch eingetragene Domain lief.

Ich wundere mich, dass die Maildomains hier anscheinend nicht gescannt wurden (keine Ergebnisse dafür).

**Comment by Skeeve** [comment]
[Scan Report(1).pdf](https://github.com/SIWECOS/siwecos-business-layer/files/3829995/Scan.Report.1.pdf)

**Comment by Lednerb** [comment]
Im Regelfall werden beim ersten Scan sowohl die `crawledUrls` als auch die `mailDomains` gescannt.

Im Zusammenhang mit https://github.com/SIWECOS/siwecos-business-layer/issues/181#issuecomment-552453121, daher schließe ich hier.
