### ISSUE TITLE
Anpassung PDF-Report Layout / Design

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-business-layer#183]
A ngehängter [Scan Report(1).pdf](https://github.com/SIWECOS/siwecos-business-layer/files/3829999/Scan.Report.1.pdf) lief heute morgen in Staging. Anscheinend ist er noch nicht für v3 angepasst, da, mindestens beim Version Scanner, keine URL angezeigt wird.

Zudem finde ich das Layout schlecht zu lesen, da die Tests sich kaum bis gar nicht von den Ergebnissen abheben.

**Comment by Skeeve** [comment]
[Scan Report(1).pdf](https://github.com/SIWECOS/siwecos-business-layer/files/3830006/Scan.Report.1.pdf)

**Comment by Lednerb** [comment]
Der Teil in der BLA ist seit einiger Zeit bereits fertiggestellt, anscheinend wurde aber in der webapp noch nicht der neue Endpunkt für `v3` integriert.

Ich öffne ein Issue dort.

**Comment by Lednerb** [comment]
> Zudem finde ich das Layout schlecht zu lesen, da die Tests sich kaum bis gar nicht von den Ergebnissen abheben.

Design / Layout müssen wir gesondert absprechen, ob und wie das angepasst werden soll.

**Comment by SniperSister** [comment]
Integration in der Webapp für die v3 ist durch https://github.com/SIWECOS/webapp/pull/85
