### ISSUE TITLE
Version-Scanner fehlt im PDF-Report

### ISSUE THREAD

**Issue by PetraStruck** [SIWECOS/siwecos-business-layer#200]
Der Kunde rodriguez.de machte uns darauf aufmerksam, dass es eine Diskrepanz zwischen dem Online-Bericht (Score 89) und dem PDF-Bericht (Score 96) gibt. Im PDF-Bericht fehlt der Version-Scanner (habe ich anhand meiner Domain festgestellt). 
![image001](https://user-images.githubusercontent.com/47851250/72793968-77457880-3c3b-11ea-9f4e-4f2e3e343f22.png)
![image004](https://user-images.githubusercontent.com/47851250/72793986-7f9db380-3c3b-11ea-99b0-f0fc65270a45.jpg)

**Comment by SniperSister** [comment]
see #201

**Comment by SniperSister** [comment]
Fix ist in 15min live!
