### ISSUE TITLE
 Issue 0042: One can change an accounts mail address without re-confirmation 

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-business-layer#22]
I just changed my accounts mail address to another address and it was stored without the need to re-confirm the new mail address.

**Comment by Skeeve** [comment]
Changing one's email address should work like this:
1) User enters new mail address
2) Mail address is checked, whether or not we already have it
2a) We do not know the address, so we send a mail for verification to the address
2b) We already have the address so we do not send a mail
3) In any case we will tell the user to check his inbox for the confirmation mail
4) The recipient of the mail clicks on the confirmation link and is redirected to the login
5) The user logs in with his new mail address and his password
6) The new mail address is confirmed

**Comment by Weegy** [comment]
New Cols for new MailAdress / Token

**Comment by Lednerb** [comment]
Abhängig von https://github.com/SIWECOS/siwecos-business-layer/issues/83

**Comment by Lednerb** [comment]
In `v2` anders gelöst, Anpassungen dennoch nötig, siehe #123
