### ISSUE TITLE
Show Overall Score and Last Scan Date already in overview

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-business-layer#24]
Please make the Overall Scan Score and the last scan result be visible without having to open the detailed results.

![example](https://user-images.githubusercontent.com/725404/38360519-ac39d944-38ca-11e8-9c06-5c1f795b5cb3.png)

**Comment by Skeeve** [comment]
Could you change this markup?

```HTML
<div class="last-scan-data"><span>Letzter Scan<br> 05.04.2018 11:24</span></div>
```
to
```HTML
<div class="last-scan-data">
<label>Letzter Scan</label>
<span class="date">05.04.2018 11:24</span>
</div>
```
That way we could freely hide the label.

Or simply remove the `Letzter Scan<br>`

**Comment by SniperSister** [comment]
I removed the text

**Comment by Skeeve** [comment]
Thanks!
