### ISSUE TITLE
Allow customer to define the user agent string

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-business-layer#26]
We already had 2 occurences of customers having issues with the user agent string we use.

Problem is: They might not be aware that their website is blocking certain strings.

Solution could be that a user is allowed to define the user agent string he wants.

While this might not help the users at once, it could improve the situation as

a) Our support could tell them what they need to change in SIWECOS so that scanning is accepted by their website
b) The poweruser could define an agent string he easily can recognize in his logs in order to filter them out

**Comment by SniperSister** [comment]
I would prefer using a generic user agent copied from a browser, that should solve the issue more or less completely without exposing the users to a field that they aren't able to understand anyway.

**Comment by ic0ns** [comment]
This does not affect the TLS-Scanner

**Comment by Lednerb** [comment]
The HSHS-DOMXSS-SCANNER is using a default browser agent, as @SniperSister recommends:

https://github.com/SIWECOS/HSHS-DOMXSS-Scanner/blob/master/app/HTTPResponse.php#L41

**Comment by Weegy** [comment]
API Übergabe des UserAgents

**Comment by Lednerb** [comment]
In der Core-API implementiert via config Option.
Sinnvoll im Einzelbetrieb, hier nicht benötigt.
