### ISSUE TITLE
PDF Mails require the domain in the subject

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-business-layer#27]
Please add the domain to the subject of PDF Notifications.

I already tried but misssing a service to retrieve the domain when I just have the scan_id

Additionally name the attachment according to the domain. So not "scanreport.pdf" but something like "siwecosreport %PROTOCOL% %DOMAIN% %ISODATE%.pdf" (e.g. "siwecosreport https byte5.de 2018-05-30.pdf")

**Comment by Weegy** [comment]
![image](https://app.gitkraken.com/api/glo/boards/5b11aa5ec9b0cf0e00930f09/attachments/5b127d2e4f33b715001af6a4)

also Subject is adapted
