### ISSUE TITLE
Notification about lowscore just once a week / Not if timeouts

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-business-layer#28]
Please do not send out notifications for low score more often than once a week.

Plase check whether or not a low score is due to a timeout and do not send to the user.

Idea: Inform the (yet to define) admin mail address. This should be configurable as long as we do not have proper monitoring for timeouts, I think this feature would be helpful.

Rough sketch:

env has to contain

ADMIN=(list-of-)admin-mail-address(es)
ADMIN_NOTIFY=list-of-events

where the "list-of-events" will be a comma separated list of possible events (like TIMEOUT).

Just a small mail to env('ADMIN') if env('ADMIN_NOTIFY') matches /\bTIMEOUT\b/.
Subject would be "%EVENT% for %DOMAIN% found at %TIME%".

For the mail body I'm not sure. Maybe url, scan_id, and scan_results.id?

PLEASE NOTICE:
This feature could be used for the mail notifications as well. If "ADMIN_NOTIFY" matches /\bLOWSCORE\b/, mails about low score should go to the admin mail address(es) instead of to the user.

**Comment by Weegy** [comment]
Fixed with commit to CA

**Comment by Skeeve** [comment]
I added 

    NOTIFICATION_LOW_SCORE=#
    NOTIFICATION_LOW_SCORE_RECIPIENTS=mail[,mail...]

for notifying the given recipients in case the score is below NOTIFICATION_LOW_SCORE.

Missing is a notification of the registered user in case NOTIFICATION_LOW_SCORE_RECIPIENTS is not set or contains "customer".

**Comment by Weegy** [comment]
If Scan_result.any(has_error) then no mail

**Comment by Weegy** [comment]
NEW ENV Vars

**Comment by Lednerb** [comment]
Abhängig von https://github.com/SIWECOS/siwecos-business-layer/issues/83

**Comment by Lednerb** [comment]
@Skeeve 
Frage zu https://github.com/SIWECOS/siwecos-core-api/issues/156 beachten.

**Comment by Lednerb** [comment]
Wird in #89 behandelt, schließe hier.
