### ISSUE TITLE
Scan of non-existing domain is not properly handled

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-business-layer#3]
Try to scan https://sdfsdfsdfghdfkgksdfgf and SIWECOS will happily try to do so without telling the user that the domain does not exist.

**Comment by Weegy** [comment]
Should we implement a small ping in front of the freescan?

let url = `https://${site.url}`;
            if (site.port && site.port != 80 && site.port != 443) url += `:${site.port}`;
            fetch(url, { mode: 'no-cors'})
              .then((resp) => {
                site.status = true;
                if (!resp.ok || resp.status != 200) site.status = false;
                if (resp.type == "opaque") site.status = true;
                self.$set(self.sites, index, site);
              })

**Comment by SniperSister** [comment]
What’s returned from the API right now in such a case?

**Comment by Weegy** [comment]
without a TLD it should respond with validation error

**Comment by Weegy** [comment]
with TLD nothing special. The scanner will try to start

**Comment by SniperSister** [comment]
Ok, in that case i would suggest adding an existence check to the core-api, validation shouldn’t be (only) frontend‘s job

**Comment by Weegy** [comment]
API return 422 when Domain is not alive. @SniperSister

**Comment by SniperSister** [comment]
Thx, adjusted the freescan accodingly
