### ISSUE TITLE
Adjustments for DOMXSS-Scanner

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/siwecos-business-layer#36]
According to the changes with https://github.com/SIWECOS/HSHS-DOMXSS-Scanner/pull/40 the test names changed as follows:

`HAS_SOURCES` to `SOURCES`
`HAS_SINKS` to `SINKS`

There are two new placeholders:

| Placeholder | Message                     |
|-------------|-----------------------------|
| **GENERAL** ||
| NO_CONTENT | The site was empty and there was nothing to scan for. |
| NO_SCRIPT_TAGS | The scanner found no `script` tags to rate. |

Please include them in the language files so that https://github.com/SIWECOS/HSHS-DOMXSS-Scanner/pull/40 can go to staging/production.

**Comment by Skeeve** [comment]
Why did you rename "HAS_SINKS" and "HAS_SOURCES"

The problem is: We need to have both now as the historical data still contains "HAS_SINK"/"HAS_SOURCES" while newer results will have "SINKS"/"SOURCES"

**Comment by Lednerb** [comment]
`HAS_SINKS` and `HAS_SOURCES` are more like a scan result, not a real *test name*.

The scanner tests for *sources* and *sinks*, the results are *NO_SOURCES_FOUND*, etc.
