### ISSUE TITLE
Missing Placeholder Values for Tests

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-business-layer#4]
The tests are missing placeholder values.

Additionally we are missing a means to provide them

* DOMXSS	
**	NO_SINKS_FOUND
**	NO_SOURCES_FOUND
**	SINKS_FOUND
**	SOURCES_FOUND
* HEADER	
**	CSP_CORRECT
**	CSP_NO_UNSAFE_INCLUDED
**	CSP_UNSAFE_INCLUDED
**	CT_CORRECT
**	CT_HEADER_WITHOUT_CHARSET
**	CT_META_TAG_SET
**	CT_META_TAG_SET_CORRECT
**	HSTS_LESS_6
**	HSTS_MORE_6
**	HSTS_PRELOAD
**	INCLUDE_SUBDOMAINS
**	XCTO_CORRECT
**	XFO_CORRECT
**	XXSS_BLOCK
**	XXSS_CORRECT
* INFOLEAK
**	CMS_ONLY
**	CMS_VERSION
**	CMS_VERSION_VULN
**	EMAIL_FOUND
**	JS_LIB_ONLY
**	JS_LIB_VERSION
**	JS_LIB_VULN_VERSION
**	NUMBER_FOUND
**	PLUGIN_ONLY
* WS_TLS
**	RC4_SUITES

I already tried to insert into siwecos.php (as a test):

`'CT_META_TAG_SET_CORRECT' => 'alles roger',`

to no avail. Still CT_META_TAG_SET_CORRECT appears in the output.

**Comment by Weegy** [comment]
Works now

**Comment by Weegy** [comment]
But I have no values for them :)

**Comment by Skeeve** [comment]
Part of the question is (Cite: "Additionally we are missing a means to provide them")

So in which form do they have to appear in siwecos.php(?) or another file?

**Comment by Weegy** [comment]
Like you did it as an example
