### ISSUE TITLE
POEditor.com anbinden per command (API neue Sprachen ziehen)

### ISSUE THREAD

**Issue by Weegy** [SIWECOS/siwecos-business-layer#40]
CRON einrichten auf den Scheduler (5min)

**Comment by Skeeve** [comment]
@ic0ns ich habe Dich assigned, weil wir uns zusammensetzen wollten, um zu sehen, welche Texte jeder Scanner benötigt und das gegebenenfalls "einzudampfen" und zu dokumentieren.

In dem Zusammenhang können wir auch überlegen, ob Scanner künftig PO Dateien mitliefern sollen, die mindestens die Englischen Texte enthalten.

**Comment by Lednerb** [comment]
Gibt es hier Fortschritte?

Wollen wir dies noch so einbinden?

Vom Cron-Job würde ich absehen, da sich so oft keine Änderung ergibt, dass dies per Cron im Live-Betrieb aktualisiert werden muss.

**Comment by Skeeve** [comment]
Cron - Nein.
Fortschritte - Nein.
Im Moment läuft es so leidlich. Mal schauen wie das funktioniert, wenn jetzt @PetraStruck das erste Mal Texte anlegt.

**Comment by Lednerb** [comment]
Update von meiner Seite:

Ich habe testweise das Projekt mal bei POEditor importiert:
https://poeditor.com/join/project/Mm4TtLCwsr

Die Freischaltung bezüglich unbegrenzter Strings, da wir ein Open Source Projekt sind, läuft.

Bei Interesse würde ich dann @Skeeve als zusätzlichen Administrator hinzufügen.


Abgesehen von der schicken Oberfläche und der Möglichkeit zu einem späteren Zeitpunkt leicht bspw. Französisch, Spanisch, Chinesisch oder Russisch mit aufzunehmen bzw. übersetzen zu lassen gibt es eine Integration für Laravel, die regelmäßig die aktuellen Strings ziehen würde:
https://github.com/SeBuDesign/Laravel-POEditor

Über die Funktion des *Proofreadings* können wir sicherstellen, dass keine ungewollten bzw. unauthorisierten Änderungen live gehen.

Wir sparen uns das ewige hin und her gemerge wegen 2er Datein und hätten zumindest für die BLA eine schicke Schnittstelle, um etwas Ordnung rein zu bekommen.

Inwiefern man dies für das Wiki einsetzen kann, müsste getestet werden.
Das Wiki kann meiner Meinung nach auch vorerst im https://github.com/siwecos/translations Repo bleiben.

**Comment by Lednerb** [comment]
Schließe hier, weil wir uns für einen anderen Weg über das siwecos/translations Repo entschieden haben, um Wiki und BLA auf dem gleichen Stand zu halten.
