### ISSUE TITLE
Multilanguage 

### ISSUE THREAD

**Issue by Weegy** [SIWECOS/siwecos-business-layer#42]
Migration für die Userdatenbank
Check der Flags im Reportprocessing

**Comment by Lednerb** [comment]
@Skeeve @Weegy da Multilanguage eigentlich bereits umgesetzt ist, ist die Frage, ob dieses Issue geschlossen werden kann?

Wahrscheinlich schon erledigt?

**Comment by Lednerb** [comment]
@Skeeve kann hier geschlossen werden? Falls ja, bitte vornehmen.

**Comment by Skeeve** [comment]
ch denke nicht, dass hier geschlossen werden kann. In der User Tabelle  sehe ich keine Möglichkeit, eine Sprachpräferenz des Users zu hinterlegen.

**Comment by Lednerb** [comment]
Implementiert in b5d6080
