### ISSUE TITLE
How to troubleshoot "Fehler beim Starten des Scans, bitte versuchen Sie es später erneut" 

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-business-layer#5]
How can we troubleshoot the reason for

"Fehler beim Starten des Scans, bitte versuchen Sie es später erneut"

which appears from time to time when trying to start a new scan.

**Comment by SniperSister** [comment]
First step is checking the API response in your browsers network tab.

**Comment by Skeeve** [comment]
403 forbidden - what now?

**Comment by Weegy** [comment]
No tokens were left.
