### ISSUE TITLE
Korrekte Recaptcha Key eintragen

### ISSUE THREAD

**Issue by SniperSister** [SIWECOS/siwecos-business-layer#59]
Siehe Slack

**Comment by Weegy** [comment]
Sind eingetragen, jedoch ohne Wirkung. Bitte mal checken für welche domains / subdomains gültig @SniperSister

**Comment by SniperSister** [comment]
Der Key ist gültig, Ich kriege aber jetzt nen 500er statt nem 422 zurück - checkst du das log?
