### ISSUE TITLE
Welcome Page missing

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-business-layer#6]
I clicked on 

`https://bla.staging2.siwecos.de/api/v1/users/activate/4t4DsmAjcwZpmZrKOyz71tY9Gt4MmtelYPA97gI738Zxk3dcjv39qvZ2hUorE00FU68JSC5zm6V5L48r2wBfHAz94k5FzMg1`

and was presented with JSON code. Nothing else.

Tested with Thunderbird and Safari on macOS.

**Comment by SniperSister** [comment]
Fixed
