### ISSUE TITLE
Mailing in k8s konfigurieren

### ISSUE THREAD

**Issue by SniperSister** [SIWECOS/siwecos-business-layer#61]
Derzeit gibt es offenbar keine ausgehenden Mails?

**Comment by Weegy** [comment]
Weil wir keinen Mailserver haben

**Comment by SniperSister** [comment]
Ich lass das mal als Mailjet reminder offen

**Comment by Weegy** [comment]
Alright :)

**Comment by Skeeve** [comment]
@MacMic kümmert sich.

**Comment by SniperSister** [comment]
@Weegy bitte Mailjet-Daten bei @MacMic erfragen und in K8s eintragen

**Comment by Weegy** [comment]
Wird gemacht

Outlook für iOS<https://aka.ms/o0ukef> beziehen

________________________________
Von: David Jardin <notifications@github.com>
Gesendet: Dienstag, November 27, 2018 8:19 AM
An: SIWECOS/siwecos-business-layer
Cc: Marcel Wege; Mention
Betreff: Re: [SIWECOS/siwecos-business-layer] Mailing in k8s konfigurieren (#61)


@Weegy<https://github.com/Weegy> bitte Mailjet-Daten bei @MacMic<https://github.com/MacMic> erfragen und in K8s eintragen

**Comment by Lednerb** [comment]
@MacMic @Weegy Neuigkeiten hierzu? Kann geschlossen werden> --> Prio:High

**Comment by SniperSister** [comment]
@Weegy iirc ist das erledigt?

**Comment by SniperSister** [comment]
@Weegy hab in den kubernetes secrets keine config dafür gefunden

**Comment by Lednerb** [comment]
`v2` wird dies anders handhaben, soweit abgeschlossen werden dann auch die Mailings konfiguriert.
