### ISSUE TITLE
PDF Reports integrieren

### ISSUE THREAD

**Issue by SniperSister** [SIWECOS/siwecos-business-layer#62]
Moin, sollten der report endpoint nicht besser in die routes/api.php hinter die usertoken middleware? Dann können wir das Token aus der eigentlich URL rausnehmen. Oder hab ich da den Usecase falsche verstanden?

**Comment by Skeeve** [comment]
Definitiv. Dazu muß dann aber auch der Teil, der die recurrent-scan Reports generiert, soweit angepaßt werden, daß er das usertoken holt.

**Comment by Lednerb** [comment]
Abhängig von https://github.com/SIWECOS/siwecos-business-layer/issues/83
