### ISSUE TITLE
502 "bad gateway" beim addNewDomain endpoint bei nicht existiernder Domain

### ISSUE THREAD

**Issue by SniperSister** [SIWECOS/siwecos-business-layer#65]
Vermutlich verwandt mit SIWECOS/siwecos-core-api#162 und Ursache von SIWECOS/webapp#9

**Comment by Lednerb** [comment]
Sollte in staging gefixt sein, bitte einmal testen.

**Comment by SniperSister** [comment]
Es wird ;) aber:

Ich brauche hier eine Möglichkeit die beiden Cases
A. Domain existiert schon in einem anderen Konto
und
B. Domain ist nicht erreichbar

zu unterscheiden. A) hat früher nen 422 geworfen, wirft gerade offenbar nen 500er, ob das gewollt ist weiß ich nicht. B) wirft jetzt nen 422er, was mir die Unterscheidungsmöglichkeit nehmen würde - kriegen wir das differenziert?

**Comment by Lednerb** [comment]
BLA und CA aktualisiert, müsste implementiert sein.

**Comment by Lednerb** [comment]
@SniperSister 

Sollte erledigt sein? Schließe hier mal.
