### ISSUE TITLE
Siegel nach Scanabschluß erstellen

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-business-layer#76]
Business Layer muß dem Core einen callback mitgeben, den Core nach Abschluß eines Scans aufruft.

In der Callback Routine muß Business Layer, sofern es sich nicht um einen freescan gehandelt hat, das Siegel erzeugen und an geeigneter Stelle (wie im Meeting besprochen Google Storage Cloud?) ablegen.

**Comment by Skeeve** [comment]
User Story dahinter Ticket in OTRS "Sehr oft offline"

"Das eingebaute SIWCOS-Siegel […] zieht die gesamte Performe der Webseiten runter!"

Unklar ist: 
Woran macht er das fest?

- Was bedeutet das für ihn 
- Wie kann man das nachvollziehen.

**Comment by Lednerb** [comment]
Done.

Alles weitere in #90
