### ISSUE TITLE
No PDF Report yet

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-business-layer#8]
Currently it's not possible to generate a PDF report.

This should be part of the SPA, as the SPA already has all the necessary parts implemented for creating nice looking reports. After all the current "Sicherheitsbericht" already is a report, let alone not an easily printed one and not yet complete with all the tips and details a user might require to fix his domain's issues.

OTOH, according to @SniperSister "PDFs in JS aren’t that much fun, I would prefer if we have that implemented in the BLA".

**Comment by Weegy** [comment]
We can define it in the BLA. Any design draft would be appreciated

**Comment by Weegy** [comment]
1st Draft done

**Comment by cgieco** [comment]
![pdfrepeport](https://user-images.githubusercontent.com/42937619/44987860-fd024e80-af88-11e8-8d8c-e504548119f7.png)

my suggestion...

**Comment by SniperSister** [comment]
@pmeco works?

**Comment by pmeco** [comment]
Works

Am 03.09.2018 um 14:56 schrieb David Jardin <notifications@github.com<mailto:notifications@github.com>>:


@pmeco<https://github.com/pmeco> works?

**Comment by SniperSister** [comment]
@Skeeve what's the endpoint to get the report?

**Comment by Skeeve** [comment]
For completeness sake: /generate/LowScoreReport/{scanId}

**Comment by SniperSister** [comment]
Der PDF report endpoint wirft noch nen 500er, zu bewundern in der Staging 

@Lednerb schaust du mal?

**Comment by Lednerb** [comment]
Fehler eingegrenzt:

```
[2018-11-23 22:54:49] docker.ERROR: Temporary files directory "/var/www/html/../temp/" is not writable {"exception":"[object] (Mpdf\\MpdfException(code: 0): Temporary files directory \"/var/www/html/../temp/\" is not writable at /var/www/html/vendor/mpdf/mpdf/src/Cache.php:23)
[stacktrace]
#0 /var/www/html/vendor/mpdf/mpdf/src/Mpdf.php(981): Mpdf\\Cache->__construct('/var/www/html/....')
#1 /var/www/html/vendor/niklasravnsborg/laravel-pdf/src/LaravelPdf/Pdf.php(37): Mpdf\\Mpdf->__construct(Array)
```

Weiterhin: Fehler in `resources/views/pdf/report.blade.php`

**Comment by Lednerb** [comment]
Schließe hier, alles weitere in #81
