### ISSUE TITLE
Recaptcha Key Staging

### ISSUE THREAD

**Issue by SniperSister** [SIWECOS/siwecos-business-layer#80]
Die Registrierung in der Staging funktioniert nicht, bekomme nen 422
> {"g-recaptcha-response":["validation.captcha"]}

ich vermute dass der Recaptcha Key in der Env nicht stimmt, der müsste identisch mit der live sein.

@Weegy checkst du das? 

/cc @Lednerb

**Comment by Lednerb** [comment]
Da ich mich fürs Testen im staging registrieren muss, habe ich das gefixt.
