### ISSUE TITLE
Saubere Trennung zwischen Core-API und BLA

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/siwecos-business-layer#83]
Momentan übernimmt die Core-API Aufgaben, für die Sie nicht gedacht ist, bspw. das verifizieren von Domains etc.

Es ist dringend notwendig, die BLA-Aufgaben in die BLA zu verschieben und die Datenbank sowie den generellen Programmablauf anzupassen.

Dies ist auch dringend Notwendig für das bessere automatisierte Testen, siehe:  #84

**Comment by SniperSister** [comment]
@Lednerb lass hierzu mal bitte sprechen bevor du damit los legst. Ich sehe das Problem genauso, wir müssen aber zum aktuellen Zeitpunkt schauen dass wir deine Stunden hier nicht verbrennen.

**Comment by Lednerb** [comment]
Ausstehend: Migrationsscript für die Datenbank erstellen.
