### ISSUE TITLE
No way to re-order an activation mail

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-business-layer#9]
There seems to be no way to ask for a resend of the activation mail. (Could be an SPA issue as well)

Background: I tested the password reset functionality with an account I (accidently) did not activate.

I could reset the password, but I could not log in as I didn't activate the account.

As I also "lost" my activation mail, there is no way for me to reactivate the account.

Proposals:

* either give the possibility to ask for a resend of the activation mail
* or count the password reset as an activation - after all the user did receive the reset mail
* or (least preferred) allow activation only within 24 hours so that a non-activated account gets cleaned up after 24h

**Comment by Weegy** [comment]
You now hava an endpoint

1. Check if user exist
2. Check if user already activated
3. resend activation

/users/activate/resend/{userid}
