### ISSUE TITLE
Endpoint wird benötigt - Aktivierungsmail erneut verschicken

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-business-layer#94]
Wir haben den Fall, daß ein Kunde die Aktivierungsmail nicht erhalten hat. Fehlkonfiguration auf seiner Seite.

Wenn man versucht sich anzumelden, wird man aufgefordert, zuerst den Account zu aktivieren. Hier wäre es gut, einen Link zu haben, der die Aktivierungsmail erneut verschickt. Dazu wird eine Endpoint benötigt.

Gut wäre es, dieses erneute Versenden kann nicht "gespammt" werden, es sollte also eine gewisse Zeit vergangen sein, bevor erneut verschickt wird. Dazu könnte das "updated_at" feld verwendet werden.

Wenn der Endpoint vorhanden ist, bitte im zugehörigen webapp ticket vermerken https://github.com/SIWECOS/webapp/issues/18

**Comment by Lednerb** [comment]
@Skeeve soll hier lediglich die Mail erneut versandt werden oder auch die Möglichkeit der Änderung der E-Mail Adresse direkt gegeben sein?

**Comment by Skeeve** [comment]
Ansich eine gute Idee, allerdings weiß ich nicht, ob das den Aufwand wert ist. Problem ist ja: User hat sich angemeldet und kann sich auch einloggen. Sonst bekäme er die Meldung nicht. Somit kennt er seine Mailadresse, die er für die Anmeldung verwendet hat. Sollte der Fall eingetreten sein, daß er auf dieser Adresse keine Mails empfangen kann und er deswegen eine andere möchte, dann sollte er sich einfach neu anmelden. Er hat ja, ausßer den Daten auf dem Anmeldeformular, noch nichts (keine Domain) eingeben können.

M.a.W. um einen netten Kollegen aus dem Team zu zititeren: Die Implementierung wäre "Verschwendung von Lebenszeit" ;)

**Comment by SniperSister** [comment]
:D

**Comment by Lednerb** [comment]
Bereits vorhanden:

HTTP-POST mit Payload `'email' => USER_EMAIL_ADDRESS` an `/api/v1/users/activate/resend` schicken.

Response-Codes:
- `200`: Mail sent
- `400`: User already activated
- `404`: User not found
