### ISSUE TITLE
Sprachwahl wird nicht berücksichtig und zu spät gespeichert

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-business-layer#96]
Beschreibung:

- Ausgangssituation: Existierender deutscher Nutzer
- Seite wird aufgerufen (Seite auf Deutsch)
- Nutzer logt sich ein (Deutsch)
- Nutzer stellt Sprache um (Deutsch -> Englisch)
- Nutzer nutzt anderen Browser und ruft die Seite auf (Deutsch)
- Nutzer logt sich ein (Seite sollte auf Englisch umschalten, bleibt aber Deutsch)
- Admin schaut in DB: Sprache ist auf Deutsch
- Nutzer geht im ersten Browser auf "My Account"
- Nutzer speichert Account Formular (Hier fehlt übrigens ein Sprachen-Feld)
- Admin schaut in DB: Sprache ist auf Englisch
- Nutzer logt sich erneut im zweiten Browser ein (der noch auf Deutsch steht)
- Seite erscheint weiterhin auf Deutsch
- Admin schaut in DB: Sprache ist weiterhin auf Englisch

Bugs:

1. Bei der Sprachwahl über die Flagge wird die Wahl für angemeldete Nutzer nicht in der DB gespeichert
2. Auf dem Account-Formular gibt es keine Sprachauswahl im Formular, die momentane Sprache wird dennoch gespeichert.
3. Die gespeicherte Sprache wird beim Einloggen nicht berücksichtigt.

**Comment by SniperSister** [comment]
@Skeeve du wirfst hier Joomla-Sprache und BLA-Sprache durcheinander.

Die Joomla-Sprache steuert:
* in welche Sprache die Seite angezeigt wird
* in welcher Sprache die SPA Sprachstrings angezeigt werden
* in welcher Sprache die Results in der SPA sichtbar sind

Maßgeblich für die jeweils gewählte Sprache ist dabei die Sprachpräferenz im Browser.

Die BLA-Sprache hingegen steuert meines Wissens nach nur genau einen Aspekt, nämlich die Sprache der automatiserten Maillings.

Daher ist das Setup derzeit so angelegt, dass die in Joomla gesetzte Sprache im Hintergrund auch in der BLA gespeichert wird um das Mailing in der selben Sprache auszugeben wie der Nutzer es auch für die Website gesehen hat.

It's not a bug, it's a feature.

**Comment by Skeeve** [comment]
Hmmm… Einigen wir uns darauf, daß es kein Bug sondern suboptimale Usability ist? ;)

**Comment by SniperSister** [comment]
Einigen wir uns doch eher darauf, dass wir da unterschiedlicher Meinung sind ;)

**Comment by Lednerb** [comment]
Ich stimme hier @SniperSister zu.

Wenn die Sprachauswahl jeweils angepasst wird, wenn ein (angemeldeter) Benutzer die Joomla-Sprache ändert, ist auch kein extra Sprachauswahl-Feld im Account-Formular notwendig.

Schließe daher hier.
