### ISSUE TITLE
Benachrichtigungslogik bei Lowscore ändern

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/siwecos-business-layer#97]
Siehe [Hier](https://github.com/SIWECOS/siwecos-business-layer/pull/92/files/7ef0988874569cf20551cbaa42dafe48bcdf008c#r254201242)

 - Diese Funktion ist zur Zeit nur für Testzwecke implementiert.
 - Es werden noch keine Mails an die Nutzer geschickt
 - Es wird ein Flag benötigt, der in staging etc. die Nachrichten nur an die in der `.env` definierten Empfänger versendet
 - Andernfalls sollen die recipients => additionalRecipients sein und unabhängig von einem Eintrag in der User-Tabelle verwendet werden können.

**Comment by Skeeve** [comment]
Vorschlag statt flag:

NOTIFICATION_LOW_SCORE_RECIPIENTS gesetzt => Nur diese werden benachrichtig

NOTIFICATION_LOW_SCORE_RECIPIENTS nicht gesetzt und
ADDITIONAL_LOW_SCORE_RECIPIENTS gesetzt => Diese werden ZUSÄTZLICH zum Owner benachrichtigt

beide nicht gesetzt => Nur owner wird benachrichtigt.

In Staging wird also NOTIFICATION_LOW_SCORE_RECIPIENTS gesetzt.

**Comment by Skeeve** [comment]
Bei Lowscore Benachrichtigung bitte auch berücksichtigen, daß

1. Maximal einmal pro Woche benachrichtigt wird.
2. Wir auch mal angedacht hatten bei Scoreverschlechterung zu benachrichtigen - Wollen wir das noch?
3. Wir nicht bei scannerausfallbedingtem Low-Score benachrichtigen wollen.

**Comment by Lednerb** [comment]
Abhängig von https://github.com/SIWECOS/siwecos-business-layer/issues/83
